From stdpp Require Import gmap tactics.
From iris_lkmm.lkmm Require Import execution_graph memory_relations rcu_graph.
From iris_lkmm.lang Require Import lkmm_core.

(** Declarative connection between an LKMM-Core run and one concrete
    candidate execution.  Reads-from and coherence are candidate choices;
    RMW pairing and direct dependencies are generated by the run. *)
Module LkmmProgramGraph.
  Export LkmmCore.
  Import LkmmMemoryRelations RcuGraph.

  Record core_candidate := CoreCandidate {
    candidate_events : event_structure;
    candidate_rf : edge_set;
    candidate_co : edge_set;
    candidate_rmw : edge_set;
    candidate_direct_addr : edge_set;
    candidate_direct_data : edge_set;
    candidate_direct_ctrl : edge_set
  }.

  Definition candidate_hb (C : core_candidate) : relation :=
    LkmmMemoryRelations.hb
      C.(candidate_events)
      C.(candidate_rmw)
      C.(candidate_rf)
      C.(candidate_co)
      C.(candidate_direct_data)
      C.(candidate_direct_addr)
      C.(candidate_direct_ctrl).

  Definition candidate_pb (C : core_candidate) : relation :=
    LkmmMemoryRelations.pb
      C.(candidate_events)
      C.(candidate_rmw)
      C.(candidate_rf)
      C.(candidate_co)
      C.(candidate_direct_data)
      C.(candidate_direct_addr)
      C.(candidate_direct_ctrl).

  Definition core_candidate_rcu_view (C : core_candidate) : LkmmExecutionGraph.graph :=
    LkmmExecutionGraph.Graph
      C.(candidate_events)
      C.(candidate_rf)
      C.(candidate_co)
      C.(candidate_rmw)
      (candidate_hb C)
      (candidate_pb C).

  Definition core_candidate_wf (C : core_candidate) : Prop :=
    event_structure_wf C.(candidate_events) /\
    rf_wf C.(candidate_events) C.(candidate_rf) /\
    co_wf C.(candidate_events) C.(candidate_co) /\
    rmw_wf C.(candidate_events) C.(candidate_rmw) /\
    direct_addr_wf C.(candidate_events) C.(candidate_direct_addr) /\
    direct_data_wf C.(candidate_events) C.(candidate_direct_data) /\
    direct_ctrl_wf C.(candidate_events) C.(candidate_direct_ctrl) /\
    rcu_matching_complete C.(candidate_events).

  Record program_graph (P : core_program) (C : core_candidate) : Prop := ProgramGraph {
    program_graph_run :
      exists actions state,
        complete_core_run P actions state /\
        state.(core_events) = C.(candidate_events) /\
        state.(core_rmw) = C.(candidate_rmw) /\
        state.(core_direct_addr) = C.(candidate_direct_addr) /\
        state.(core_direct_data) = C.(candidate_direct_data) /\
        state.(core_direct_ctrl) = C.(candidate_direct_ctrl);
    program_graph_wf : core_candidate_wf C
  }.

  Definition lkmm_consistent (C : core_candidate) : Prop :=
    coherence C.(candidate_events) C.(candidate_rf) C.(candidate_co) /\
    atomicity C.(candidate_events) C.(candidate_rmw) C.(candidate_rf) C.(candidate_co) /\
    happens_before C.(candidate_events) C.(candidate_rmw)
      C.(candidate_rf) C.(candidate_co)
      C.(candidate_direct_data) C.(candidate_direct_addr) C.(candidate_direct_ctrl) /\
    propagation C.(candidate_events) C.(candidate_rmw)
      C.(candidate_rf) C.(candidate_co)
      C.(candidate_direct_data) C.(candidate_direct_addr) C.(candidate_direct_ctrl) /\
    rcu_consistent (core_candidate_rcu_view C).

  (** Allocation is an invariant of the run itself.  Exact agreement with a
      well-formed candidate then gives the generated RMW and dependency
      relations their relational well-formedness guarantees. *)
  Theorem program_graph_execution_invariants P C :
    program_graph P C ->
    exists actions state,
      complete_core_run P actions state /\
      core_allocation_wf state /\
      state.(core_events) = C.(candidate_events) /\
      state.(core_rmw) = C.(candidate_rmw) /\
      state.(core_direct_addr) = C.(candidate_direct_addr) /\
      state.(core_direct_data) = C.(candidate_direct_data) /\
      state.(core_direct_ctrl) = C.(candidate_direct_ctrl) /\
      rmw_wf state.(core_events) state.(core_rmw) /\
      direct_addr_wf state.(core_events) state.(core_direct_addr) /\
      direct_data_wf state.(core_events) state.(core_direct_data) /\
      direct_ctrl_wf state.(core_events) state.(core_direct_ctrl).
  Proof.
    intros [(actions & state & Hrun & Hevents & Hrmw_eq & Haddr_eq &
      Hdata_eq & Hctrl_eq) (_ & _ & _ & Hrmw & Haddr & Hdata & Hctrl & _)].
    pose proof Hrun as Hcomplete_run. destruct Hrun as [Hsteps Hcomplete].
    exists actions, state. split_and!; try done.
    - apply (core_run_allocation_wf P actions state). exact Hsteps.
    - by rewrite Hevents, Hrmw_eq.
    - by rewrite Hevents, Haddr_eq.
    - by rewrite Hevents, Hdata_eq.
    - by rewrite Hevents, Hctrl_eq.
  Qed.

  Module ProgramGraphTests.
    Definition writer : stmt := SStore StoreOnce (EConst 0) (EConst 1).
    Definition reader : stmt := SLoad 0 LoadOnce (EConst 0).

    Definition program : core_program :=
      CoreProgram {[0%nat := 0%Z]} {[0%nat := writer; 1%nat := reader]}.

    Definition init_write : event := EInitWrite 0 0%Z.
    Definition write : event :=
      EAgent 0 0 (LMemory AccessWrite AccessOnce NotRmw 0 1%Z).
    Definition read : event :=
      EAgent 1 0 (LMemory AccessRead AccessOnce NotRmw 0 1%Z).

    Definition sample_events : event_structure := {[0 := init_write; 1 := write; 2 := read]}.
    Definition sample_rf : edge_set := {[(1, 2)]}.
    Definition sample_co : edge_set := {[(0, 1)]}.

    Definition candidate : core_candidate :=
      CoreCandidate sample_events sample_rf sample_co ∅ ∅ ∅ ∅.

    Local Lemma sample_lookup_cases eid ev :
      lookup_event sample_events eid = Some ev ->
      (eid = 0 /\ ev = init_write) \/
      (eid = 1 /\ ev = write) \/
      (eid = 2 /\ ev = read).
    Proof.
      intros Hlookup. unfold lookup_event, sample_events in Hlookup.
      apply lookup_insert_Some in Hlookup as [[-> Hevent] | [_ Hlookup]].
      - left. naive_solver.
      - apply lookup_insert_Some in Hlookup as [[-> Hevent] | [_ Hlookup]].
        + right. left. naive_solver.
        + apply lookup_singleton_Some in Hlookup. right. right. naive_solver.
    Qed.

    Local Lemma sample_events_wf : event_structure_wf sample_events.
    Proof.
      intros eid1 eid2 agent index label1 label2 Hlookup1 Hlookup2.
      destruct (sample_lookup_cases eid1 _ Hlookup1) as
        [(Heid1 & Hevent1) | [(Heid1 & Hevent1) | (Heid1 & Hevent1)]];
        destruct (sample_lookup_cases eid2 _ Hlookup2) as
        [(Heid2 & Hevent2) | [(Heid2 & Hevent2) | (Heid2 & Hevent2)]];
        subst eid1; subst eid2;
        unfold init_write, write, read in Hevent1, Hevent2; congruence.
    Qed.

    Local Lemma sample_rf_wf : rf_wf sample_events sample_rf.
    Proof.
      split_and!.
      - intros source target Hrf.
        unfold rf, edge_relation, sample_rf in Hrf.
        assert (source = 1 /\ target = 2) as [-> ->] by set_solver.
        exists write, read, 1%Z. split_and!; try reflexivity.
        exists 0. split; reflexivity.
      - intros source1 source2 target Hrf1 Hrf2.
        unfold rf, edge_relation, sample_rf in Hrf1, Hrf2. set_solver.
      - intros target target_event Hlookup Hread.
        destruct (sample_lookup_cases target target_event Hlookup) as
          [(-> & ->) | [(-> & ->) | (-> & ->)]]; try done.
        exists 1. unfold rf, edge_relation, sample_rf. set_solver.
    Qed.

    Local Lemma sample_co_wf : co_wf sample_events sample_co.
    Proof.
      split_and!.
      - intros source target Hco.
        unfold co, edge_relation, sample_co in Hco.
        assert (source = 0 /\ target = 1) as [-> ->] by set_solver.
        exists init_write, write. split_and!; try reflexivity.
        exists 0. split; reflexivity.
      - intros source Hco. unfold co, edge_relation, sample_co in Hco. set_solver.
      - intros source middle target Hco1 Hco2.
        unfold co, edge_relation, sample_co in Hco1, Hco2. set_solver.
      - intros source target source_event target_event
          Hsource Htarget Hsource_write Htarget_write Hlocation Hne.
        destruct (sample_lookup_cases source source_event Hsource) as
          [(-> & ->) | [(-> & ->) | (-> & ->)]];
          destruct (sample_lookup_cases target target_event Htarget) as
          [(-> & ->) | [(-> & ->) | (-> & ->)]];
          unfold co, edge_relation, sample_co; set_solver.
      - intros loc (eid & Hloc). unfold event_has_location in Hloc.
        apply bind_Some in Hloc as (ev & Hlookup & Hloc).
        destruct (sample_lookup_cases eid ev Hlookup) as
          [(-> & ->) | [(-> & ->) | (-> & ->)]];
          simpl in Hloc; assert (loc = 0) as -> by congruence;
          exists 0, 0%Z; reflexivity.
      - intros loc source target (source_value & Hsource) (target_value & Htarget).
        destruct (sample_lookup_cases source _ Hsource) as
          [(-> & Hevent1) | [(-> & Hevent1) | (-> & Hevent1)]];
          destruct (sample_lookup_cases target _ Htarget) as
          [(-> & Hevent2) | [(-> & Hevent2) | (-> & Hevent2)]];
          try discriminate; done.
      - intros source target loc target_event
          (source_value & Hsource) Htarget Hwrite Hlocation Hne.
        destruct (sample_lookup_cases source _ Hsource) as
          [(-> & Hevent) | [(-> & Hevent) | (-> & Hevent)]]; try discriminate.
        destruct (sample_lookup_cases target _ Htarget) as
          [(-> & ->) | [(-> & ->) | (-> & ->)]];
          unfold co, edge_relation, sample_co; set_solver.
    Qed.

    Local Lemma empty_rmw_wf : rmw_wf sample_events (∅ : edge_set).
    Proof.
      split_and!; unfold rmw, edge_relation.
      - intros source target Hedge. set_solver.
      - intros source target1 target2 Hedge1 Hedge2. set_solver.
      - intros source1 source2 target Hedge1 Hedge2. set_solver.
      - intros eid ev Hlookup Hwrite Hmarked.
        destruct (sample_lookup_cases eid ev Hlookup) as
          [(Heid & Hevent) | [(Heid & Hevent) | (Heid & Hevent)]];
          subst eid; subst ev; done.
    Qed.

    Local Lemma candidate_wf : core_candidate_wf candidate.
    Proof.
      split_and!.
      - apply sample_events_wf.
      - apply sample_rf_wf.
      - apply sample_co_wf.
      - apply empty_rmw_wf.
      - intros source target Hedge. set_solver.
      - intros source target Hedge. set_solver.
      - intros source target Hedge. set_solver.
      - split; reflexivity.
    Qed.

    Local Lemma sample_complete_run :
      exists actions state,
        complete_core_run program actions state /\
        state.(core_events) = sample_events /\
        state.(core_rmw) = (∅ : edge_set) /\
        state.(core_direct_addr) = (∅ : edge_set) /\
        state.(core_direct_data) = (∅ : edge_set) /\
        state.(core_direct_ctrl) = (∅ : edge_set).
    Proof.
      exists [CoreEmit 0; CoreObserve 1 1%Z]. eexists. split.
      - split.
        + eapply CoreRunCons.
          { eapply StepStore; try reflexivity. by eexists. }
          eapply CoreRunCons.
          { eapply StepLoad; try reflexivity. by eexists. }
          constructor.
        + intros agent thread Hlookup. unfold thread_complete.
          destruct (decide (agent = 0)) as [-> | Hne0].
          * simpl in Hlookup. injection Hlookup as <-. done.
          * destruct (decide (agent = 1)) as [-> | Hne1].
            -- simpl in Hlookup. injection Hlookup as <-. done.
            -- simpl in Hlookup. simplify_map_eq.
      - split_and!; reflexivity.
    Qed.

    Example two_agent_program_graph : program_graph program candidate.
    Proof. constructor; [apply sample_complete_run | apply candidate_wf]. Qed.
  End ProgramGraphTests.

End LkmmProgramGraph.
